### PR TITLE
fix: misc bugfixes to reminders

### LINKED ISSUE #6776: Chandler bug: Updating a Reminder Removes Associated `user_notification_channels`
**Describe the bug**
Using the most recent build of Chandler, a pretty major issue occurs when updating a contact reminder which has been scheduled for a notification channel. While going through the update handler, all notification channels which that reminder is using are removed. Note: Not just the `contact_reminder_scheduled` records, but the overall `user_notification_channel` records. This is most definitely not the expected behavior. DB Engine: MySQL, hosting: Docker

**Screenshots**
image
image

**Additional context**
Relevant code snippet: https://github.com/monicahq/monica/blob/chandler/app/Domains/Contact/ManageReminders/Services/UpdateContactReminder.php#L84-L87

### PR DESCRIPTION
**Pull request by evanlihou**
- Updating an existing reminder no longer deletes the user's notification channels
- Finishing the setup of a Telegram connection now triggers a scheduling of the user's notifications, making behavior consistent with how email verification works

It's been about 7 years since I've touched any code that uses Laravel, happy to make any updates you feel would improve the quality of this PR 🙂 

Fixes #6776

### CODE REVIEW

File: tests/Unit/Domains/Contact/ManageReminders/Services/UpdateContactReminderTest.php [hunk 1]
```diff
@@ -33,6 +33,44 @@ public function it_updates_a_reminder(): void
...
+            'label' => 'birthdate',
+            'day' => 29,
+            'month' => 10,
+            'year' => 1981,
+            'type' => ContactReminder::TYPE_ONE_TIME,
+            'frequency_number' => null,
+        ];
+
+        (new UpdateContactReminder())->execute($request);
+        (new UpdateContactReminder())->execute($request);
```
Comment (evanlihou) [inline tests/Unit/Domains/Contact/ManageReminders/Services/UpdateContactReminderTest.php:67]: I'm not entirely sure why, but in the context of the unit test, the old implementation would fail only if `UpdateContactReminder` was executed twice

**Comment by evanlihou** [comment]
@djaiss @asbiin Thanks for all the work you do on this project! The issue that I opened for these bugs got closed, so I figured I'd try to implement a fix on my own.

The combination of these two issues made the experience of using Telegram reminders in Chandler very frustrating. Please review this small PR at your earliest convenience 🙂

**Review by asbiin — CHANGES_REQUESTED** [review]

**Review by asbiin — APPROVED** [review]
