### PR TITLE
Fix 719

### LINKED ISSUE #719: Error when updating timezone
When I try to update the timezone in the account settings page in app.monicahq.com, I get the following error: 

> The email has already been taken.

I didn't edit the email field.

### PR DESCRIPTION
**Pull request by djaiss**
Close #719

### CODE REVIEW

File: app/Http/Requests/SettingsRequest.php [hunk 1]
```diff
@@ -26,7 +26,7 @@ public function rules()
         return [
             'first_name' => 'required|max:255',
             'last_name' => 'required|max:255',
-            'email' => 'required|email|max:2083|unique:users,email,'. $this->id,
```
Comment (JakariaBlaine) [inline app/Http/Requests/SettingsRequest.php]: Was StyleCI failing just for that space?
@djaiss
