### PR TITLE
fix: fix search when prefix table is used

### LINKED ISSUE #3090: SQLSTATE[42S22]: Column not found: 1054
**Describe the bug**
I have set the `DB_PREFIX=monica_` and when trying to load `/public/people/list` I get `SQLSTATE[42S22]: Column not found: 1054`

**Screenshots**
https://i.imgur.com/dtFh6Mh.png

**Which version are you using:**
Latest version, 2.15.2

**Additional context**
Here's the full error message...

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'monica_monica_contacts.id' in 'field list' (SQL: select `monica_monica_contacts`.`id`, `monica_monica_contacts`.`first_name`, `monica_monica_contacts`.`middle_name`, `monica_monica_contacts`.`last_name`, `monica_monica_contacts`.`nickname`, `monica_monica_contacts`.`gender_id`, `monica_monica_contacts`.`account_id`, `monica_monica_contacts`.`created_at`, `monica_monica_contacts`.`updated_at`, `monica_monica_contacts`.`is_partial`, `monica_monica_contacts`.`is_starred`, `monica_monica_contacts`.`avatar_source`, `monica_monica_contacts`.`avatar_adorable_url`, `monica_monica_contacts`.`avatar_gravatar_url`, `monica_monica_contacts`.`avatar_default_url`, `monica_monica_contacts`.`avatar_photo_id`, `monica_monica_contacts`.`default_avatar_color` from `monica_contacts` where `monica_contacts`.`account_id` = 4 and `monica_contacts`.`account_id` is not null and `is_partial` = 0 and `is_active` = 1 and `is_dead` = 0 and `monica_contacts`.`account_id` = 4 AND (`monica_contacts`.`first_name` LIKE '%%' or `monica_contacts`.`middle_name` LIKE '%%' or `monica_contacts`.`last_name` LIKE '%%' or `monica_contacts`.`nickname` LIKE '%%' or `monica_contacts`.`description` LIKE '%%' or `monica_contacts`.`job` LIKE '%%') order by `monica_contacts`.`is_starred` desc, `first_name` desc limit 30 offset 0)
```

Everything else seems fine on a quick run through...

### PR DESCRIPTION
**Pull request by asbiin**
This fix #3090

### CODE REVIEW

File: app/Http/Controllers/ContactsController.php [hunk 1]
```diff
@@ -511,7 +511,7 @@ public function search(Request $request)
             return;
         }
 
-        $results = SearchHelper::searchContacts($needle, 20, '`contacts`.`created_at`');
+        $results = SearchHelper::searchContacts($needle, 20, '`'.DB::connection()->getTablePrefix().'contacts`.`created_at`');
```
Comment (djaiss) [inline app/Http/Controllers/ContactsController.php]: @asbiin berk.

Can't we do an helper for this instead?

Comment (asbiin) [reply app/Http/Controllers/ContactsController.php]: Yes good idea!
