### PR TITLE
Fix gravatar support

### LINKED ISSUE #897: Gravatar support
As a Monica user, it's helpful to see people's faces as a reminder of who they are. However, manually uploading avatar images for each contact can be pretty tedious.

Instead, it would be helpful if Monica supported [Gravatar](https://en.gravatar.com/). If I enter an email address for my contact, then Monica could use the Gravatar image until I upload some override.

Somewhat related #715

### PR DESCRIPTION
**Pull request by asbiin**
This will close #897

#### Before submitting the PR
- [x] Read the [CONTRIBUTING document](https://github.com/monicahq/monica/blob/master/CONTRIBUTING.md) before submitting your PR.
- [x] If the PR is related to an issue or fix one, don't forget to indicate it.
- [x] Make sure that the change you propose is the smallest possible.
- [ ] Screenshots are included if the PR changes the UI.
- [ ] If you change the UI, make sure the user experience is consistent with the current interface.

#### Code-related tasks
- [x] Tests added for this feature/bug.
- [ ] Impact on the seeders.
- [ ] Impact on the API.

#### If the code changes the SQL schema
- [ ] Impact on account export.
- [x] Impact on importing data with `vCard` and `.csv` files.
- [ ] Impact on account reset and deletion.

#### Other tasks
- [x] [CHANGELOG](https://github.com/monicahq/monica/blob/master/CHANGELOG) entry added, if necessary, under `UNRELEASED`.
- [ ] [CONTRIBUTORS](https://github.com/monicahq/monica/blob/master/CONTRIBUTORS) entry added, if necessary.
- [ ] If it's relevant, add the documentation about your feature in the README file.
- [ ] Indicate `[wip]` in the title of the PR it is is not final yet. Remove `[wip]` when ready. Otherwise the PR will be considered complete and rejected if it's not working.

### CODE REVIEW

File: app/Contact.php [hunk 1]
```diff
@@ -884,6 +884,25 @@ public function getAvatarSource()
         return 'internal';
     }
 
+    /**
+     * Update the gravatar, using the firt email found.
+     */
+    public function updateGravatar()
```
Comment (djaiss) [inline app/Contact.php]: We could unit test the new methods in `Contact.php`, what do you think?

Comment (asbiin) [reply app/Contact.php]: Yes that's why I've added "TODO" on the comment of the PR ;)

Comment (asbiin) [reply app/Contact.php]: I've added some tests
