### PR TITLE
fix: fix contact information update

### LINKED ISSUE #2390: Description is not saved
I tried creating new contacts and editing contacts in the hosted version of Monica. I found the following bugs:
- photo uploads fail, an S3 URL is generated but that URL shows "Access Denied" when trying to access it directly
- any value entered in the description field is not saved and/or not displayed

### PR DESCRIPTION
**Pull request by asbiin**
This fix #2390
I've also removed all `$contact` services properties.

### CODE REVIEW

File: app/Services/Contact/Contact/CreateContact.php [hunk 1]
```diff
@@ -72,44 +70,47 @@ public function execute(array $data) : Contact
...
 
-        $this->contact->setAvatarColor();
-
-        $this->contact->save();
+        $contact->setAvatarColor();
+        $contact->save();
 
         // we query the DB again to fill the object with all the new properties
-        return Contact::find($this->contact->id);
+        $contact->refersh();
```
Comment (guessit-dev) [inline app/Services/Contact/Contact/CreateContact.php]: refresh?

Comment (asbiin) [reply app/Services/Contact/Contact/CreateContact.php]: :D Of course !

Comment (asbiin) [reply app/Services/Contact/Contact/CreateContact.php]: Thank you @guessit-dev
