### PR TITLE
fix: change APP_TRUST_PROXIES to APP_TRUSTED_PROXIES 

### LINKED ISSUE #6024: APP_TRUST_PROXIES middleware still broken resulting in bad URLs
I'm still seeing exactly the same problem as https://github.com/monicahq/monica/issues/5954 even after upgrading to a version of `monica:fpm` that includes that fix.

I spent some time looking at the code and googling, and I think https://stackoverflow.com/questions/40722331/laravel-asset-method-doesnt-return-https is the fundamental problem. I'm definitely sending correct `Host` and `X-Forwarded-Proto: https` headers - I'm not sure if the code in https://github.com/monicahq/monica/pull/5955/files actually fixes this - there's this project: https://github.com/fideloper/TrustedProxy that implements a Laraval middleware called `TrustedProxy` that looks more complicated than the one in the above pull request. I'm not super-knowledgable about php, but I can't tell how the middleware included in monica is supposed to tell that it needs to look at the `X-Forwarded-Proto` header to have the `asset` function generate correct URLs.

Also the documentation in https://github.com/monicahq/monica/blob/main/docs/installation/ssl.md is out of date, since it refers to the `APP_TRUSTED_PROXIES` variable which doesn't work.

### PR DESCRIPTION
**Pull request by GregTCLTK**
This pull request fixes the issue mentioned in #5954, which was wrongfully closed after the merge of #5955. It also fixes #6024

#### Before submitting the PR
- [x] Read the [CONTRIBUTING document](https://github.com/monicahq/monica/blob/main/CONTRIBUTING.md) before submitting your PR.
- [x] If the PR is related to an issue or fix one, don't forget to indicate it.
- [x] Create your PR as draft if it is not final yet. Mark it as ready... when it’s ready. Otherwise the PR will be considered complete and rejected if it's not working.

### General checks
- [x] Make sure that the change you propose is the smallest possible.
- [x] The name of the PR should follow the [conventional commits guideline](https://github.com/monicahq/monica/blob/main/docs/contribute/readme.md#conventional-commits) that the project follows.

#### Other tasks
- [x] [CONTRIBUTORS](https://github.com/monicahq/monica/blob/main/CONTRIBUTORS) entry added, if necessary.
- [x] If it's relevant and worth mentioning, create a changelog entry for this change. The changelog entry will appear inside the UI for all users to see. To know if your change is worth the creation of a changelog entry, [read the documentation](https://github.com/monicahq/monica/blob/main/docs/administrators/tips.md#when-is-it-relevant-to-create-a-changelog-entry).
- [x] Don't forget to [ask for a free account](mailto:regis@monicahq.com) on https://monicahq.com as anyone who contributes can request a free account.

### CODE REVIEW

File: config/app.php [hunk 1]
```diff
@@ -149,7 +149,7 @@
     |
     */
 
-    'trust_proxies' => env('APP_TRUST_PROXIES'),
+    'trust_proxies' => env('APP_TRUSTED_PROXIES'),
```
Comment (asbiin) [inline config/app.php:152]: It needs to be fixed as
```suggestion
    'trust_proxies' => env('APP_TRUSTED_PROXIES', env('APP_TRUST_PROXIES')),
```

**Review by asbiin — CHANGES_REQUESTED** [review]

**Review by asbiin — APPROVED** [review]
