### PR TITLE
Remove Dusk from Composer

### LINKED ISSUE #805: 1.6.0 - Composer install fails
Unfortunately the upgrade to 1.6.0 breaks the app completely, again.
Running `composer install` after pulling all changes leads to the following error:
```
In DuskServiceProvider.php line 43:
It is unsafe to run Dusk in production.
```
I don't know why Dusk is considered to be loaded in a production environment. This makes absolutely no sense.

Are there any tests that are running before a release?

----

**Update**
Removing `"laravel/dusk": "^2.0",` from the composer.json file and then running `composer update --no-dev --prefer-dist` solves the problem.

### PR DESCRIPTION
**Pull request by djaiss**
Fix #805

### CODE REVIEW

File: app/Providers/AppServiceProvider.php [hunk 1]
```diff
@@ -31,8 +30,9 @@ public function boot()
      */
     public function register()
     {
-        if ($this->app->environment('local', 'testing')) {
-            $this->app->register(DuskServiceProvider::class);
-        }
+        // Comment out as we are removing Dusk from the repository
+        // if ($this->app->environment('local', 'testing')) {
```
Comment (asbiin) [inline app/Providers/AppServiceProvider.php]: MAJOR Remove this commented out code. [rule](https://sonarcloud.io/coding_rules#rule_key=php%3AS125)

**Comment by asbiin** [comment]
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
